# Site settings
title: algoquant Home
description: algoquant's Home Page on GitHub
name: algoquant.github.io
comments: true
disqus: algoquant

# Build settings
theme: minima
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://algoquant.github.io/" # the base hostname & protocol for your site

my_name: Jerzy Pawlowski (algoquant)
email: jp3900@n_y_u.edu
github: algoquant
twitter: quantwise
linkedin: https://www.linkedin.com/in/jerzypawlowski
stackoverflow: http://stackoverflow.com/users/3225258/algoquant

avatar: https://avatars.githubusercontent.com/algoquant
email: jp3900@nyu.edu
github:  algoquant
twitter: quantwise

include: ["_pages"]
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', node_modules', 'package.json', 'Gruntfile.js', 'README.md']
gems:
  - jekyll-sitemap
  - jekyll-paginate

# navigation bar
navbar:
  title: "algoquant Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html

# list of links in the navigation bar
navbar-links:
  About Me: "about"
  Resources:
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "https://algoquant.github.io/"

