# Site settings
include: ["_pages"]

# Name of your site (displayed in the header)
author:
  name: Jerzy Pawlowski (algoquant)
  email: jp3900@n_y_u.edu
  github: algoquant
  twitter: quantwise
  linkedin: https://www.linkedin.com/in/jerzypawlowski
  stackoverflow: http://stackoverflow.com/users/3225258/algoquant
include: ["_pages"]
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', node_modules', 'package.json', 'Gruntfile.js', 'README.md']
gems:
  - jekyll-sitemap
  - jekyll-paginate
name: algoquant.github.io
title: R technologies for systematic investing
description: > # this means to ignore newlines until "baseurl:"
  This is algoquant's main web page on github.
avatar: https://avatars.githubusercontent.com/algoquant

url: "https://algoquant.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# navigation bar
navbar:
  title: "algoquant Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html

# list of links in the navigation bar
navbar-links:
  About Me: "about"
  Resources:
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "https://algoquant.github.io/"

# Build settings
theme: minima
markdown: kramdown
kramdown:
  input: GFM